import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {calculate,defaults} from '../../dist/supernode/engine.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),dir=path.join(root,'dist/supernode');
const read=async name=>JSON.parse(await fs.readFile(path.join(dir,name),'utf8'));
const csv=rows=>'\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');
const models=await read('models.json'),hardware=await read('hardware.json'),coverage=await read('model-coverage.json'),tasks=await read('workloads.json');
const results=[];
const weightFormats=['BF16','FP8-E4M3','FP8-E5M2','MXFP8','INT8','MXFP4','NVFP4','INT4','NF4'],activationFormats=['BF16','FP8-E4M3','FP8-E5M2','MXFP8','INT8'];
for(const m of models)for(const h of hardware.slice(0,3))for(const phase of tasks.map(v=>v.id))for(const format of weightFormats)for(const actFormat of activationFormats)for(const n of [64,512,2048]){
 if(phase==='lora'&&(format!=='BF16'||actFormat!=='BF16')||phase==='qlora'&&(!['MXFP4','NVFP4','INT4','NF4'].includes(format)||actFormat!=='BF16'))continue;
 const training=!['prefill','decode'].includes(phase);
 const x={...defaults,phase,format,actFormat,savedActBytes:2,commBytes:2,cacheLayout:'hf-expanded',tp:8,pp:1,dp:n/8,ep:64,etp:1,sp:8,zero:training?3:0,domain:h.domain,hbmGiB:h.hbmGB*1e9/2**30,hbmGBps:h.hbmGBps,intraGBps:h.intraGBps,interGBps:h.interGBps,tflops:null,actCoeff:training?4:12,recompute:training?1:0,workspaceGiB:8,gatherGiB:8};
 const r=calculate(m,x);if(r.errors.length)throw Error(r.errors.join(';'));
 results.push({model:m.id,kind:m.kind,platform:h.name,unit:h.unit,phase,weight_format:format,activation_compute_format:actFormat,activation_coefficient:x.actCoeff,cache_layout:x.cacheLayout,cache_elements_or_bytes_per_MLA_layer:r.kvWidthUsed,peak_MLA_layers:r.maxMlaLayers,peak_KDA_layers:r.maxKdaLayers,PP_stage_cache_counts:JSON.stringify(r.cacheStageCounts),devices:n,domains:r.domains,TP:x.tp,PP:x.pp,DP:x.dp,EP:x.ep,ETP:x.etp,EDP:r.edp,ZeRO:x.zero,B:x.batch,T_configured:x.tokens,effective_new_tokens:r.effectiveNewTokens,history_context:x.context,peakCacheTokens:r.peakCacheTokens,saved_activation_bytes:x.savedActBytes,communication_payload_bytes:x.commBytes,reserve:x.reserve,HBM_GiB:x.hbmGiB,weight_GiB:r.weightsGiB,gradient_GiB:r.gradientGiB,optimizer_GiB:r.optimizerGiB,master_GiB:r.masterGiB,activation_GiB:r.activationGiB,KV_GiB:r.kvGiB,KDA_GiB:r.kdaGiB,conv_GiB:r.convGiB,workspace_gather_GiB:r.workspaceGiB,imbalance_extra_GiB:r.imbalanceExtraGiB,total_GiB:r.totalGiB,usable_GiB:r.usableGiB,capacity_only:r.capacityFits?'预算内，未验证可运行':'预算超出',unique_state_lower_devices:r.stateOnlyLowerCards,source_ids:m.source+';'+h.refs,assumptions:'snapshot: packing=.02,imbalance=1.1,adapter=1B(nonexpert),grad2/master4/optimizer8B,savedActivationBytes='+x.savedActBytes+',communicationBytes='+x.commBytes+',activationCoefficient='+x.actCoeff+',actFormatOnlyCompute='+actFormat+',SP8,liveMicro1,workspace8GiB,gather8GiB,KV2B/KDA4B/conv4B,cacheShard1; no timing rank; format support unverified'});
}
const heads=Object.keys(results[0]);await fs.writeFile(path.join(dir,'scenario-matrix.csv'),csv([heads,...results.map(v=>heads.map(k=>v[k]))]));await fs.writeFile(path.join(dir,'scenario-matrix.json'),JSON.stringify(results,null,2));
await fs.mkdir(path.join(dir,'models'),{recursive:true});
for(const c of coverage){const m=models.find(v=>v.id===c.id),rows=[['模型',c.name,'原模型ID',c.id],['专题范围',c.scope,'模型配置来源',c.config_source],['总逻辑参数',m?.total??'未导入超节点基线','依据',m?.source??'需逐模型核对'],['激活线性参数代理',m?.active??'未核验','用途','仅线性计算近似，不用于权重容量'],['路由专家参数',m?.routed??'未核验','用途','与非专家分别TP/EP/DP分片'],['超节点公式','N=TP*PP*DP; EDP=TP*DP/(ETP*EP)','范围','并行budget，不是后端已支持'],['全参训练','参数+梯度+optimizer+master+activation+workspace','8/4bit','矩阵精度不能代替全部训练状态'],['LoRA / QLoRA','冻结底座 + 目标adapter状态 + 激活 + 反量化工作区','需补','r、目标层、格式与设备kernel'],['推理','分别prefill/decode；权重+KV+状态+工作区','缓存','仅K3使用本专题混合MLA/KDA公式；其他模型不可套用'],['设备支持','见hardware.csv及precision-support.csv','性能','未设备实测'],['交互情景','https://limjiunnbin.github.io/model-research-atlas/supernode/index.html?model='+c.id,'优化清单','../ascend-priorities.csv'],['保留缺口',c.required_inputs,'旧数据','本补充未改写原XLSX/CSV']];await fs.writeFile(path.join(dir,'models',c.id+'-supernode.csv'),csv([['字段','值','补充字段','说明'],...rows]));}
console.log(results.length+' scenario snapshots; '+coverage.length+' per-model scope supplements');
